# Generated by Django 5.2.5 on 2026-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(null=True)),
                ('min_players', models.IntegerField(null=True)),
                ('max_players', models.IntegerField(null=True)),
                ('playing_time', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
