# Generated by Django 5.2.4 on 2026-05-15 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGames',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('released_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('playing_time', models.IntegerField()),
                ('weight', models.FloatField()),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='games.boardgames')),
            ],
        ),
        migrations.DeleteModel(
            name='BoardGame',
        ),
    ]
