# Generated by Django 5.2.4 on 2026-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_boardgames_gamedetails_delete_boardgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
